### ISSUE TITLE
Error while integrating 1.5.3-alpha01

### ISSUE THREAD

**Issue by shriharsha-srb** [ismai117/kottie#1]
<img width="1554" alt="Screenshot 2024-02-13 at 23 13 05" src="https://github.com/ismai117/kottie/assets/110283322/ed55f013-4c4b-433f-8dba-e65b6b24531d">

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':composeApp:transformIosMainCInteropDependenciesMetadataForIde'.
> Could not resolve all files for configuration ':composeApp:iosMainResolvableDependenciesMetadata'.
   > Could not find io.ktor:ktor-client-darwin:3.0.0-wasm2.
     Required by:
         project :composeApp
         project :composeApp > io.github.ismai117:kottie:1.5.3-alpha01
   > Could not find io.ktor:ktor-client-core:3.0.0-wasm2.
     Required by:
         project :composeApp > io.github.ismai117:kottie:1.5.3-alpha01

**Comment by ismai117** [comment]
try out 1.4.3, 1.5.3-alpha01 is a pre-release version

**Comment by ismai117** [comment]
if you want to try out kottie on wasm, make sure to add  

maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental")  in settings.gradle
