### ISSUE TITLE
Transparent background not working in IOS

### ISSUE THREAD

**Issue by JamshedAlamQaderi** [ismai117/kottie#15]
Hello @ismai117 ,

I am trying to set transparent background to lottie animation but it's always white. I think you've added necessary parameter to be able to set transparent background in ios.

```kotlin
Column(modifier = Modifier.fillMaxSize().background(Color.Green)) {
    val composition = rememberKottieComposition(
        spec = KottieCompositionSpec.File(Res.getUri("files/animation.json"))
    )
    val animationState by animateKottieCompositionAsState(
        composition = composition,
        speed = 1f,
        iterations = iterations
    )
    KottieAnimation(
        modifier,
        composition,
        progress = { animationState.progress },
        backgroundColor = Color.Transparent
    )
}
```

![simulator_screenshot_3FB0BEA0-FB25-45F6-A21F-BCBF244F15EF](https://github.com/ismai117/kottie/assets/54829362/3ba1e264-d622-40a3-b264-80db801a74a7)

By the way, thank you for this awesome library

**Comment by ismai117** [comment]
Hi @JamshedAlamQaderi make sure the  backgroundColor matches the container background color

```Kotlin 
Column(modifier = Modifier.fillMaxSize().background(Color.Green)) {
    val composition = rememberKottieComposition(
        spec = KottieCompositionSpec.File(Res.getUri("files/animation.json"))
    )
    val animationState by animateKottieCompositionAsState(
        composition = composition,
        speed = 1f,
        iterations = iterations
    )
    KottieAnimation(
        modifier,
        composition,
        progress = { animationState.progress },
        backgroundColor = Color.Green
    )
}
```

**Comment by JamshedAlamQaderi** [comment]
@ismai117 I know that. But I have a loading animation which will show on top of the screen and need to show only animation

**Comment by ismai117** [comment]
@JamshedAlamQaderi can you show me the android version

**Comment by ErickSorto** [comment]
@ismai117 Hey I am having the same problem too. 

This is how it looks on IOS
![Screenshot 2024-06-08 at 8 32 33 AM](https://github.com/ismai117/kottie/assets/85327212/e551ef39-09ce-4b98-a1b4-53a78541fe3f)

This is how it looks on Android
![image](https://github.com/ismai117/kottie/assets/85327212/a3b13ccb-50f4-47dc-b66d-121c80714257)

**Comment by ismai117** [comment]
Unfortunately, transparent background doesn't work at the moment, you can check out 

https://github.com/JetBrains/compose-multiplatform/issues/3154

**Comment by JamshedAlamQaderi** [comment]
@ismai117 i have used skiko implementation from desktop module. I think you should use skiko implementation until this issue has been fixed.

**Comment by ErickSorto** [comment]
@ismai117 Is there any workarounds for this issue? I am not sure how to go about fixing this issue.

**Comment by ismai117** [comment]
@ErickSorto Unfortunately No

**Comment by frangulyan** [comment]
> @ErickSorto Unfortunately No, for simple lottie animations you can do the following
> 
> ```kotlin
>  MaterialTheme {
>         Box(
>             modifier = modifier
>                 .fillMaxSize()
>                 .background(MaterialTheme.colorScheme.background),
>             contentAlignment = Alignment.Center
>         ) {
> 
>             KottieAnimation(
>                 composition = composition,
>                 progress = { animationState.progress },
>                 modifier = modifier
>                     .fillMaxWidth()
>                     .height(200.dp),
>                 backgroundColor = MaterialTheme.colorScheme.background
>             )
> 
>         }
>     }
> ```

For some reason, this doesn't work on iOS for my animation. I use backgroundColor = Color.Green and still got white background. It works on Android though. Any limitations on supported lottie features?
