### ISSUE TITLE
Not work, build not success/ or any Exeption ! Dependencies is the problem

### ISSUE THREAD

**Issue by toffeantyri** [ismai117/kottie#16]
kotlin = "2.0.0"
compose = "1.6.2"
ktor = "2.3.9"
kottie = "1.8.6"

build failure: compose multiplatform resources : ResourceItem : passed value size, offset.
ok: set kottie = "1.7.3"
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout

what version of ktor/compose/kotlin needed?

**Comment by ismai117** [comment]
Try ktor version 2.3.11, for web/wasm try version 3.0.0-wasm2

**Comment by toffeantyri** [comment]
dont(
 ktor = 2.3.11
target: jvm

Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout

**Comment by ErickSorto** [comment]
I am having dependency issues too

ktor = "2.3.11" I also tried "3.0.0-wasm2" same message
kotlin = "2.0.0"
compose = "1.6.7"
kottie = "1.8.6"

I keep getting:
* What went wrong:
Execution failed for task ':composeApp:transformIosTestCInteropDependenciesMetadataForIde'.
> Could not resolve all files for configuration ':composeApp:iosTestResolvableDependenciesMetadata'.
   > Could not find io.ktor:ktor-client-darwin:3.0.0-wasm2.
     Required by:
         project :composeApp
   > Could not find io.ktor:ktor-client-core:3.0.0-wasm2.
     Required by:
         project :composeApp
   > Could not find io.ktor:ktor-client-darwin:3.0.0-wasm2.
     Required by:
         project :composeApp > io.github.ismai117:kottie:1.8.6
   > Could not find io.ktor:ktor-client-core:3.0.0-wasm2.
     Required by:
         project :composeApp > io.github.ismai117:kottie:1.8.6

**Comment by ismai117** [comment]
@ErickSorto you need to add maven("https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental") inside settings.gradle for kottie to work using wasm

**Comment by ismai117** [comment]
@toffeantyri @toffeantyri use the latest build version 1.9.6-alpha02, you don't need to add anything in settings.gradle
