### ISSUE TITLE
Compose resources version not matches

### ISSUE THREAD

**Issue by toffeantyri** [ismai117/kottie#17]
kotlin = "2.0.0"
compose = "1.6.2"
kottie = "1.9.6-alpha02"

I use compose multiplatform resources (unstable api)

Task :shared:compileDebugKotlinAndroid failed :
 
e: .../shared/generated/resources/Drawable0.kt:132:61 No value passed for parameter 'offset'.
e: .../shared/generated/resources/Drawable0.kt:132:61 No value passed for parameter 'size'.

I think - the version of compose dont match, and my version resources not matches too.

without kottie build success.

would do you tell me, your version of compose please

**Comment by ismai117** [comment]
Kottie is using the latest compose-plugin version 1.6.11
