### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout

### ISSUE THREAD

**Issue by brandy-kay** [ismai117/kottie#19]
when working with Kottie version 1.8.6 on JVM the project fails with this error Caused by: java.lang.ClassNotFoundException: io.ktor.client.plugins.HttpTimeout

when I remove the Kottie Library my project worked well

kotlin version 2.0.0
compose multiplatform version 1.6.10

**Comment by ismai117** [comment]
@brandy-kay try out the latest build 1.9.6-alpha02

**Comment by brandy-kay** [comment]
@ismai117 this now works perfectly
