### ISSUE TITLE
reverseOnRepeat not working for iOS

### ISSUE THREAD

**Issue by carlosftorres** [ismai117/kottie#21]
I have this animation state 
```
val animationState by animateKottieCompositionAsState(
        composition = composition,
        isPlaying = playing,
        iterations = 3,
        reverseOnRepeat = true,
        speed = 0.7f
    )
```
trying to use `reverseOnRepeate = true`, in android it works fine but in iOS behaves the same if the property is true or false.

Could you add support for `reverseOnRepeat` on iOS?

Thanks!

**Comment by ismai117** [comment]
Hi @carlosftorres setAnimationRepeatAutoreverses() is deprecated on lottie iOS - https://developer.apple.com/documentation/uikit/uiview/1622501-setanimationrepeatautoreverses?changes=_6

I will try my best to sort it out

**Comment by ismai117** [comment]
reverseOnRepeat functionality is now added to the latest kottie release 2.0.0
