### ISSUE TITLE
Compose Multiplatform, white background instead of transparent on Ios.

### ISSUE THREAD

**Issue by Kognitivist** [ismai117/kottie#22]
@OptIn(ExperimentalResourceApi::class)
@Composable
fun Kottie(resPath: String) {
    var animation by remember { mutableStateOf("") }

    LaunchedEffect(Unit) {
        animation = Res.readBytes(resPath).decodeToString()
    }
    val composition = rememberKottieComposition(spec = KottieCompositionSpec.File(animation))
    val animationState by animateKottieCompositionAsState(
        composition = composition,
        isPlaying = true,
        iterations = Int.MAX_VALUE
    )

    KottieAnimation(
        composition = composition,
        progress = { animationState.progress },
        modifier = Modifier,
        backgroundColor = Color.Transparent
    )
}
![Simulator Screenshot - iPhone 15 - 2024-08-09 at 16 22 02](https://github.com/user-attachments/assets/7503d589-9f45-4c3b-8e64-94c09f8a1b4f)

on android OK
![Screenshot_20240809_162137](https://github.com/user-attachments/assets/8359faa3-5639-4fe7-be2a-3cc3077326e4)

**Comment by ismai117** [comment]
https://github.com/ismai117/kottie/issues/9

**Comment by ismai117** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/3154

**Comment by DarHayun1** [comment]
Hi @ismai117 is there any workaround to display an animation on iOS without the white background?
