### ISSUE TITLE
iOS background color not change

### ISSUE THREAD

**Issue by parkuiery** [ismai117/kottie#26]
Android|iOS
--|--|
![image](https://github.com/user-attachments/assets/23e67415-a8cf-46c7-afcd-9d7509a6d0e5)|![image](https://github.com/user-attachments/assets/cda89e57-9fc6-4ade-a81d-90af722e5715)

I use kottie version 2.0.0

**Comment by ismai117** [comment]
https://github.com/ismai117/kottie/issues/5
