### ISSUE TITLE
Any API to start/restart the animation manually?

### ISSUE THREAD

**Issue by armond1978** [ismai117/kottie#3]
I couldn't find any method on `KottieAnimationState` to manually control the animation (start, restart, change the progress percentage, etc). Can you help me understand how this can be done?

**Comment by ismai117** [comment]
Hi @armond1978 I've updated the readme to explain how to use Kottie, and I also added the (restartOnPlay) option to the upcoming version (1.5.3), which will be released at the end of this week, hopefully .

**Comment by armond1978** [comment]
Hi @ismai117. Thanks for your prompt reply.

Using the updated readme, I could control the start of the animation once. But when it ends, I can not restart it (setting `isPlaying` to false and then back to true doesn't work). The workaround I used was to increase the iteration by one when I need to play it again! It works but there needs to be a more straight forward way of doing this.

**Comment by ismai117** [comment]
@armond1978 Version 1.5.3 has been released, and I've added the restartOnPlay option to animateKottieCompositionAsState(). The default value is true, so the animation will restart once it's finished. 

Try it out and let me know how it goes, please. thanks!

**Comment by armond1978** [comment]
@ismai117 What repository have you uploaded this new version to? The latest version I see on maven central repo is `1.5.3-alpha02`.

**Comment by ismai117** [comment]
Check releases, it should show v1.5.3

**Comment by armond1978** [comment]
Now I'm seeing this new version for some of the platforms... `kottie-desktop` and `kottie-wasm-js` are still not there. Even Nexus repo manager shows `1.5.3-alpha02` as the latest for these platforms.

**Comment by ismai117** [comment]
Desktop is kottie-jvm, wasm is not included in this version. I will be releasing a different version for wasm with the latest changes

**Comment by ismai117** [comment]
@armond1978 check out the pre-release v1.6.3-alpha01, works with wasm!

**Comment by armond1978** [comment]
@ismai117 I appreciate your very prompt action! And yes, it works :-) Thank you!
