### ISSUE TITLE
Expose android properties to Kottie

### ISSUE THREAD

**Issue by LaatonWalaBhoot** [ismai117/kottie#4]
There is an option of `maintainOriginalImageBounds`  in lottie-android
Right now Kottie does not expose this option
Setting this fixes the base64 image issue
Would it possible to have this?

Issue with image
As you can see the image at the center has its bounds all wrong
This is fixed in native android lottie by setting the above property

![Screenshot_20240217-073007](https://github.com/ismai117/kottie/assets/30817376/a0ee90ff-6521-4b99-a80c-70e74be00900)

**Comment by ismai117** [comment]
can you provide resources regarding the maintainOriginalImageBounds, I don't understand ti

**Comment by LaatonWalaBhoot** [comment]
Would this be helpful?

https://github.com/airbnb/lottie-android/blob/f0f24b95502a96511e1a6475b8fa222adefc44c8/lottie/src/main/java/com/airbnb/lottie/LottieAnimationView.java#L956

**Comment by ismai117** [comment]
Can I just ask why your animation background is set to Black? It should be transparent
