### ISSUE TITLE
Animation background is white instead of transparent on iOS

### ISSUE THREAD

**Issue by rdsarna** [ismai117/kottie#5]
Animation file - 
[loading.json](https://github.com/ismai117/kottie/files/14493831/loading.json)

Example - 
https://github.com/ismai117/kottie/assets/7789307/0e014884-f86c-4c12-9294-78f7d79196a2

Please refer to the above animation JSON file and the example video recording. The animation has a transparent background but it renders with a white background when running on iOS. The example video is taken by using the animation file in the sample app.

**Comment by ismai117** [comment]
Hi @rdsarna, transparent background doesn't work on the UIKitview at the moment, so you have to set the background for the KottieAnimation composable the same as the container's background color. Here's an example.

```Kotlin
MaterialTheme {
        Scaffold(
            containerColor = MaterialTheme.colorScheme.onSurfaceVariant
        ) { paddingValues ->
            Box(
                modifier = modifier
                    .padding(paddingValues)
                    .fillMaxSize(),
                contentAlignment = Alignment.Center
            ) {

                KottieAnimation(
                    composition = composition,
                    progress = { animationState.progress },
                    modifier = modifier.size(300.dp),
                    backgroundColor = MaterialTheme.colorScheme.onSurfaceVariant
                )

            }
        }
    }
```

Result: 

https://github.com/ismai117/kottie/assets/88812838/5c0d0073-6fc9-467d-b6cd-3f82faf9b168

**Comment by rdsarna** [comment]
That fixed the issue. Thanks a lot!

**Comment by nowiwr01w** [comment]
Hi @ismai117 
I tried what you said, but it kinda doesn't work. Here's an example:

Left button = iOS, Right button = Android
You can see on iOS the white empty square at the "first" animation frame that Android doesn't have

https://github.com/ismai117/kottie/assets/39140585/6f28e572-2c30-4a1c-871a-47e92ca95fd6

I guessed there was something wrong with my color management, but even when I set the Kottie background to Color.Black, I initially still saw a white square at the first animation frame. Only afterwards could I see the animation start on a black background

![CleanShot 2024-05-09 at 21 24 37](https://github.com/ismai117/kottie/assets/39140585/2789e537-7ce4-45f0-99f0-1d0af73a93c7)
![CleanShot 2024-05-09 at 21 25 01](https://github.com/ismai117/kottie/assets/39140585/a2e92eec-b657-4491-9c65-6de04e0ba08f)

My code:
```kotlin
KottieAnimationView(
    type = KottieCompositionSpecType.JsonString(animationJsonString),
    animationSettings = KottieAnimationSettings(backgroundColor = Color.Black),
    onCompleteCallback = onCompleteCallback,
    modifier = Modifier
        .size(24.dp)
        .background(Color.Black)
)
    
KottieAnimation(
    modifier = modifier,
    composition = composition,
    progress = { animationState.progress },
    backgroundColor = animationSettings.backgroundColor
)
```

I don't know exactly how to handle a transparent background on iOS, but maybe [this](https://developer.apple.com/documentation/uikit/uibackgroundconfiguration#3807696) could help?

```swift
class TransparentViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()

        // view
        self.view.backgroundColor = UIColor.clear
        
        // subview
        let subview = UIView()
        subview.backgroundColor = UIColor.clear
        self.view.addSubview(subview)
    }
}
```

**Comment by ismai117** [comment]
https://github.com/JetBrains/compose-multiplatform/issues/3154
