### ISSUE TITLE
 Animation doesn't play on iOS with compose 1.6.10 dev builds

### ISSUE THREAD

**Issue by OSemenovBoyarka** [ismai117/kottie#9]
Starting from [this](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1493) build - when I run app on iOS - all animations show white screen (I use `KottieCompositionSpec.File` everywhere).

Android works fine.

The previous build ([1.6.10-dev1457](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10-dev1457)) works fine.

I've also tried to load animation file from resources (debugger confirms it loads) and use `KottieCompositionSpec.JsonString` - issue is the same.
Not sure if I should post this issue here or to `compose-multiplatform` repo.

**Comment by ismai117** [comment]
Hi @OSemenovBoyarka, so for the first problem check out https://github.com/ismai117/kottie/issues/5 I've explained the solution there.

with the other issue, are you trying to use kottie with 1.6.10-dev1457 build?

**Comment by ismai117** [comment]
@OSemenovBoyarka no worries! So at the moment, Kottie is using version 1.6.1, so it's not compatible with 1.6.10-dev1457

Maybe that's the reason why it's not working. I haven't tried 1.6.10-dev1457, so I don't know if there's a way around it
